### ISSUE TITLE
revalidateField fails with rules added via addRequiredGroup

### ISSUE THREAD

**Issue by shawnheide** [horprogs/Just-validate#101]
Thanks for your time and work on this project, it's been helpful in migrating from jQuery. When using `revalidateField`, rules added with `addRequiredGroup` fail since they aren't in `this.fields`. https://github.com/horprogs/Just-validate/blob/b1519dc264bdf3051d4e9f6c93fb05dadbe8ae7e/src/main.ts#L805

I thought about adding a validateGroup method, but `clearFieldStyle` and `renderFieldError` both rely on `this.fields` too, so those would need a "groups" version as well. Does anyone have thoughts on a clean way to do this? My preference would be to use `revalidateField` for both fields and groups.

**Comment by horprogs** [comment]
Hey! Thanks! I think it's possible to add `revalidateGroup` method (btw `validateGroup` already exists).
We don't actually need to use `clearFieldStyle` as we don't have styles for groups.
Also we already have `renderGroupLabel` method.

So it should be easy to implement a new method, I will look into that today-tomorrow.

**Comment by horprogs** [comment]
Added the `revalidateGroup` method. Hope it helps.

**Comment by shawnheide** [comment]
Wow, thanks for the quick reply and implementation, I really appreciate it.
