### ISSUE TITLE
Type '"required"' is not assignable to type 'Rules'

### ISSUE THREAD

**Issue by cesarcarmona** [horprogs/Just-validate#103]
Hello i have this error
`Type '"required"' is not assignable to type 'Rules'`

`interfaces.d.ts(56, 5): The expected type comes from property 'rule' which is declared here on type 'FieldRuleInterface'`

I already investigated but I can't find the error thanks

**Comment by horprogs** [comment]
Hi, you should export `Rules` directly from 'just-validate' and use it as:

```
rule: Rules.Required
```

or

```
rule: 'required' as Rules
```
