### ISSUE TITLE
Question: Is there a way to validate individual fields `onChange` or `onBlur`?

### ISSUE THREAD

**Issue by homestar9** [horprogs/Just-validate#108]
I'm just getting started with Just-Validate, so please forgive this "noob" question, but is there a way to validate an individual field after the value changes or when a field loses focus?

For example, let's say you have an email input field.  After the user types in a bad value and clicks off of the field, Is there a way to validate just that field to give the user instant feedback?

I have found that this type of user experience can be beneficial on longer forms so users can correct mistakes as they go rather than having to go back to the beginning.  Thanks!

**Comment by horprogs** [comment]
`onBlur` we don't have yet, unfortunately. But there is `onValidate` callback where you could check the state of your fields. Together with `validateBeforeSubmitting` config flag user could input something and get immediate feedback, without clicking on Submit button.

https://codesandbox.io/s/just-validate-template-forked-k30wc5?file=/index.html

<img width="903" alt="image" src="https://user-images.githubusercontent.com/14051960/218258752-3eb171fa-0f5f-4032-9fe4-c66f59e152ed.png">

**Comment by homestar9** [comment]
Thank you. I will play around with it and post back if I come up with an easy to implement workaround.
