### ISSUE TITLE
Possible to required radiobutton ?

### ISSUE THREAD

**Issue by simonghx** [horprogs/Just-validate#12]
Is it possible to add a requirement on the radiobuttons ? There is for a gender select in a form for example.. 
It's possible for a checkbox but I didn't see anything for the radiobuttons.. 

KR

**Comment by simonghx** [comment]
Hi ! Thanks very much, your work is very helpful for mine ! :)

**Comment by horprogs** [comment]
Please, check v1.3.0, I've added feature for validate radio buttons. 
If you like this plugin, pls star project, it will be nice to me :) 

https://github.com/horprogs/Just-validate/releases/tag/v1.3.0

**Comment by simonghx** [comment]
I've just checked the new feature and it's working very well ! Thank you very much for your work 😄
