### ISSUE TITLE
Method unlockForm

### ISSUE THREAD

**Issue by TFuriosiITDM** [horprogs/Just-validate#121]
The method unlockForm doesn't work. I don't know if it is intentionally written like this but i've tried to use this method and it doesn't work.

My form locks automatically during the validation because i've created JustValidate instance with default lock option, but it doesn't get unlocked.

```typescript
  unlockForm(): void {
    const elems: NodeListOf<HTMLInputElement> = this.form!.querySelectorAll(
      'input, textarea, button, select'
    );
    for (let i = 0, len = elems.length; i < len; ++i) {
// This is wrong.
      if (
        elems[i].getAttribute('data-just-validate-fallback-disabled') !== 'true'
      ) {
        elems[i].removeAttribute('disabled');
      }
      elems[i].style.pointerEvents = '';
      elems[i].style.webkitFilter = '';
      elems[i].style.filter = '';
    }
  }
```
Should be
```typescript
  unlockForm(): void {
    const elems: NodeListOf<HTMLInputElement> = this.form!.querySelectorAll(
      'input, textarea, button, select'
    );
    for (let i = 0, len = elems.length; i < len; ++i) {
      if (
        elems[i].getAttribute('data-just-validate-fallback-disabled') === 'true'
      ) {
        elems[i].removeAttribute('disabled');
      }
      elems[i].style.pointerEvents = '';
      elems[i].style.webkitFilter = '';
      elems[i].style.filter = '';
    }
  }
```

**Comment by horprogs** [comment]
Could you please provide some example where it doesn't work for you? You could check the working example here https://just-validate.dev/examples#async-validation

The line you mentioned as wrong actually works fine. It's needed to avoid enabled fields if they have been disabled before (not by the library).

**Comment by TFuriosiITDM** [comment]
Sorry i was wrong, it was a problem with react-strict-mode. Now it works fine. Thank You!
