### ISSUE TITLE
Cannot use this library in core typescript project

### ISSUE THREAD

**Issue by sangtrandev00** [horprogs/Just-validate#125]
Is this library support for typescript project. I am currently use this typescript project for my validation
It will throw the error like this:

`
Could not find a declaration file for module 'just-validate'. 'd:/FPT POLYTECHNIC/WEB DESIGN CURRICULUM/SEMESTER 5/SEMESTER 5 - Front End/WEB502 - Lap trinh TypeScript - SP21/ASM_SETUP/typescript-webpack-asm/node_modules/just-validate/dist/just-validate.production.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/just-validate` if it exists or add a new declaration (.d.ts) file containing `declare module 'just-validate';`ts(7016)
`

**Expected behavior**

Any body confront this issue, Give me some more solution

**Comment by horprogs** [comment]
Hey, how are you using the library? Are you importing it in your project?

**Comment by horprogs** [comment]
What Typescript version do you use? Try using Typescript 4, not 5

**Comment by sangtrandev00** [comment]
Thanks. I am using typescript v5. To fix my issue, just ignore it, I used // @ts-ignore in the library, so I can use the lib
