### ISSUE TITLE
Trigger validation and error messages via javascript 

### ISSUE THREAD

**Issue by AndiLeni** [horprogs/Just-validate#137]
Hello,

I want to trigger the validation and displaying of error messages via javascript.
My form is submitted via javscript and hence no submit button is present on my page.
Is it somehow possible to achieve this @horprogs ?
I tried using the validate() function, but this does not display the error messages.

Thanks and kind regards

**Comment by PiemP** [comment]
you have to call [revalidate function](https://just-validate.dev/docs/methods/revalidate). If you have registered fields you should see relative error messages.
