### ISSUE TITLE
Validation Suggestion

### ISSUE THREAD

**Issue by ukozdan** [horprogs/Just-validate#17]
Hi, just a suggestion. This plug-in could be more versatile if you changed lines 756-761 of [app.js](https://github.com/horprogs/Just-validate/blob/master/src/js/app.js) such that no inline styles are set and options allow the setting of custom CSS classes, such as [Bootstrap 4's custom validation classes](https://getbootstrap.com/docs/4.3/components/forms/#custom-styles). 

BTW, how does one specify JSON for the built-in AJAX handler?

**Comment by horprogs** [comment]
Hi! Thank you for your suggestion, I'll think about it.

Unfortunately, no way for specify JSON :( I'm going to add this property in next version

**Comment by horprogs** [comment]
Custom classes for fields and labels were added in https://github.com/horprogs/Just-validate/releases/tag/v2.0.0
