### ISSUE TITLE
Method to check if the form is invalid

### ISSUE THREAD

**Issue by aloayzab88** [horprogs/Just-validate#19]
Is there any method or way to check if the form is invalid? I tried submitHandler but that only work when the form is valid.

**Comment by horprogs** [comment]
Hi! Sorry for answer delaying. No, there is no this method. I think I'll develop it in next version.

**Comment by aloayzab88** [comment]
Thanks for the answer. The question is related to accessibility. Right now I'm running another function after 100ms to check if the error class exist and then focus the input with the error but is not reliable. It turns really problematic when there is a remote rule because the time to check if the input is valid varies.

**Comment by horprogs** [comment]
Please, check the version v1.5.0. I've added method 
``` 
invalidFormCallback: function (errors) {
    console.log(errors);
},
```
and property `focusWrongField`, if you set it in true, after submitting the first incorrect field will be focused.

https://github.com/horprogs/Just-validate/releases/tag/v1.5.0

**Comment by aloayzab88** [comment]
Thanks, I endend using a mutation observer to check the changes on the disabled attribute of the submit button but I tested your new version and it works perfectly. Thank you very much!
