### ISSUE TITLE
Not working on select tag

### ISSUE THREAD

**Issue by aloayzab88** [horprogs/Just-validate#24]
If you submit the form with all the required inputs empty and the select an option the select stays as invalid. 
And if you change the value of any other input the selects of the form will constantly get marked as invalid.

**Comment by stuartc1** [comment]
I put a fix in for this on my fork:
https://github.com/stuartc1/Just-validate/commit/e37f33a6c81c044da36656db67609ed57457f163

**Comment by horprogs** [comment]
Fixed in https://github.com/horprogs/Just-validate/releases/tag/v2.0.0

**Comment by Defite** [comment]
4.3.0 and it's still broken. any clues?
