### ISSUE TITLE
Checkbox group not supported.

### ISSUE THREAD

**Issue by stuartc1** [horprogs/Just-validate#25]
Single checkboxes work just fine, but if you want to have a group using an array name (name="mycheckgroup[]"), the validation half works. It shows error on last option, and requires that all fields are selected (I think that's wrong, it should just be at least one).

The big problem is the ajax event handler doesn't pass the checkbox array values though. It just ends up with a single value of "true".

I would suggest adding the same support as the radio group for this (in regards to validation).And passing array values through the handler. 

I will look at putting a fix in my fork as it looks like this has gone stale at the moment.

**Comment by mardorfv** [comment]
I have the same issue and would like to continue using it.

**Comment by horprogs** [comment]
Thanks guys, added in https://github.com/horprogs/Just-validate/releases/tag/v2.0.0
