### ISSUE TITLE
Re validate on change a select element

### ISSUE THREAD

**Issue by rafaelkapela** [horprogs/Just-validate#26]
I just added this after line 590. Just to revalidate a input after change a option on select.

`				if (item.type === 'select-one') {
					item.addEventListener('change', function (ev) {
                        delete _this2.result[item.name];
                        _this2.validateItem({
                            name: item.name,
                            value: item.value,
                            group: []
                        });
                        _this2.renderErrors();
					});
				}`

**Comment by horprogs** [comment]
Fixed in https://github.com/horprogs/Just-validate/releases/tag/v2.0.0
