### ISSUE TITLE
Broken CDN link in just-validate.dev

### ISSUE THREAD

**Issue by IlyaMur** [horprogs/Just-validate#28]
CDN link in main site is broken. 
`<script src="https://unpkg.com/just-validate@2.0.0-beta.2/dist/just-validate.production.min.js"></script>`

**Comment by horprogs** [comment]
Thanks. Deployed the new site version. Correct link is `<script src="https://unpkg.com/just-validate@2.0.0-beta.6/dist/just-validate.production.min.js"></script>`
