### ISSUE TITLE
Apply Min and Max Length Validations Only if there is Value

### ISSUE THREAD

**Issue by shivam091** [horprogs/Just-validate#31]
I came across a situation that I want to apply min and max length validations to fields only if there is a value entered for that field.

Example:

minLength - 2
maxLength - 50

I added these validation rules for the field but I want to apply these validations only if there is a value within that textbox.

Empty string is just fine and if string isn't empty then apply min and max length validations.

Is there a way to achive this ?

**Comment by horprogs** [comment]
It should be possible in `3.0.0` version. I've changed the logic a bit. Now, to validate for required you should define `required` rule directly. If the value is empty - validation will pass.

**Comment by shivam091** [comment]
Fantastic. I checked your recent change you did in v3.0.0 and it's covering the solution for the problem I was facing.

Thank you.
