### ISSUE TITLE
Any plan for Implementing Date Validation Rule

### ISSUE THREAD

**Issue by protaskz-in** [horprogs/Just-validate#33]
Hi. 

I went through the documentation of this plugin. I found almost all frequently used validation rules except date. 

Do you have any plan to implement it ? If date validation rule is added, I think, I would be a plus point this library will have.

If you have a plan to implement it, I would be very happy to use this plugin for validations. 

It will be very great if you can plan for some frequent options, viz., min date, max date, depending on value of other field (eg. validation of end date depending on start date), required date validations, date format and separator validations, etc

Please let me know your comment on this.

**Comment by horprogs** [comment]
Hi, yeah this is a good suggestion. I will work on it

**Comment by protaskz-in** [comment]
I think, my way is then clear for moving with this plugin. I hope that next versions will also be with support for date validations. I think, this is really fantastic that you are going to add support for this one..

**Comment by horprogs** [comment]
Implemented the first version, I made it as a plugin (https://github.com/horprogs/just-validate-plugin-date) to avoid extending the library size.

Now it's possible to validate for the date format, and check if date is before/after. I think it's enough for the basic usage, not sure what else to add. But anyway it's not going to be complicated. If you have any suggestions: would be happy to hear.

Usage:

```
import JustValidatePluginDate from 'just-validate-plugin-date';

validation
  .addField('#date-start', [
    {
      plugin: JustValidatePluginDate(() => ({
        format: 'dd/MM/yyyy',
      })),
      errorMessage: 'Date should be in dd/MM/yyyy format (e.g. 15/10/2021)',
    },
  ])
  .addField('#date-between', [
    {
      plugin: JustValidatePluginDate(() => ({
        format: 'dd/MM/yyyy',
      })),
      errorMessage: 'Date should be in dd/MM/yyyy format (e.g. 15/10/2021)',
    },
    {
      plugin: JustValidatePluginDate((fields) => ({
        format: 'dd/MM/yyyy',
        isAfter: fields['#date-start'].elem.value,
        isBefore: fields['#date-end'].elem.value,
      })),
      errorMessage: 'Date should be between start and end dates',
    },
  ])
  .addField('#date-end', [
    {
      plugin: JustValidatePluginDate(() => ({
        format: 'dd/MM/yyyy',
      })),
      errorMessage: 'Date should be in dd/MM/yyyy format (e.g. 15/10/2021)',
    },
  ]);
```

Examples:
For plain text inputs:
https://just-validate.dev/examples/#date-text-input

For date inputs:
https://just-validate.dev/examples/#date-date-input

**Comment by protaskz-in** [comment]
Hi,

Thanks for looking into this. I looked into the examples and I think, basic needs are covered in new plugin as well. Only one thing I could tell you is what if date is not mandatory ? At present, I am being forced to keep it mandatory because I am able to see that every time i am getting error as "Date should be in yyyy-mm-dd format (e.g. 2021-12-30).".

I think, this should not happen. Date format and date validation rules must be fired only if that field is filled with some value.
It would be great if you provide support for existing `required` rule separatly on date fields.

Thanks in advance.

**Comment by horprogs** [comment]
Thanks, a great point. I decided to let the plugin to handle all rules, that's why I added `required` option to the plugin config. I think it's fine.

```
validation.addField("#date", [
  {
    plugin: JustValidatePluginDate(() => ({
      required: true,
      format: "dd/MM/yyyy",
    })),
  },
]);

```

https://just-validate.dev/examples/#date-date-input

**Comment by protaskz-in** [comment]
Great... Thank you.
