### ISSUE TITLE
Apply `customRegex` rule only if Field is filled up with Value

### ISSUE THREAD

**Issue by protaskz-in** [horprogs/Just-validate#34]
Hi,

I am being forced to keep those fields mandatory if those fields are bound with rule `customRegex`.

Example:

If I have 3 rules:

`minLength`, `maxLength`, `customRegex` but not `required` then in this case I expect that three rules must be fired only if there is value and as the field is not mandatory, If there is not value in that text field, validation should pass. but this is happening with minLength and maxLength but not in case of customRegex.

Ideally, `customRegex` rule should be fired only if there is some value present for that particular field.

Let me know what do you think on this.

Thanks in advance !

**Comment by horprogs** [comment]
Thanks, that makes sense. Fixed in `3.2.2`

**Comment by protaskz-in** [comment]
Looks perfect ! Thank you for your enhancements.
