### ISSUE TITLE
Same set of validations on Multiple Form Selectors

### ISSUE THREAD

**Issue by protaskz-in** [horprogs/Just-validate#37]
Hi,

I think, plugin instance can be bound only to single form selector at a time. But suppose we have same set of fields but there form selectors are different (e.g., create-project, edit-project) then in that case, we need to iterate loop on those selector or form tag itself and place validations inside the loop to take validations in to effect. 

Do you have any such plans to add this support or any other perfect solution the plugin has ?

e.g. validation object

```javascript

formValidation = new JustValidate(".create-project, .edit-project", {
  errorFieldCssClass: "is-invalid",
  errorLabelCssClass: "invalid-feedback",
  focusInvalidField: true,
  lockForm: false,
  tooltip: {
    position: "top"
  },
}).onSuccess((event) => {
  event.preventDefault();
  axios({
    ...
  });
}).onFail((fields) => {
});
```
and then selector can be form class or name or id of users choice.

Thanks in advance.

**Comment by horprogs** [comment]
Hi! Thank you for this suggestion. I had a look to implement this, but there are some complications with adding fields. Now it should be one field on the page with selector you defined in `.addField` method. For now you cannot have 2 forms on the page with fields with the same selectors (if you use class names as a selector). If you use id as a field selector - this is even worse, because you cannot have 2 the same ids on the page. It means you cannot just have array of forms with fields with the same ids. 

So, not sure this is worth to implement this feature now, I'll think about it. There is a quick workaround without changing the library:

```
['#create-project, #edit-project'].forEach((selector) => {
  const formValidation = new JustValidate(selector, {
    errorFieldCssClass: 'is-invalid',
    errorLabelCssClass: 'invalid-feedback',
    focusInvalidField: true,
    lockForm: false,
    tooltip: {
      position: 'top',
    },
  })
    .addField(`${selector}-name`, [
      {
        rule: 'required',
      },
    ])
    .onSuccess((event) => {
      event.preventDefault();
    })
    .onFail((fields) => {});
});
```

**Comment by protaskz-in** [comment]
Well. Thank you. I was actually came across such situation that there are two forms with same fields but on multiple pages but there ID are different and class selectors are also diffirent.

But in previous days, I also added some work arounds for fulfilling what I was required.

My main moto was only that I was afraid of writing same rules for two time for two forms having different selectors but I thought, I can add my own class/ID selector for the form and my implementation can be like this..

```javascript
formValidation = new JustValidate(".project-form", {
  errorFieldCssClass: "is-invalid",
  errorLabelCssClass: "invalid-feedback",
  focusInvalidField: true,
  lockForm: false,
  tooltip: {
    position: "top"
  },
}).onSuccess((event) => {
  event.preventDefault();
  axios({
    ...
  });
}).onFail((fields) => {
});

```

Now with this I am able to validate my fields on both ".create-project" and ".update-project" as I had mentioned earlier. 

So you are right what you mentioned in your reply. You can look it later by leaving workarounds here till that time.

Once again thank you.
