### ISSUE TITLE
Error Message Target Append?

### ISSUE THREAD

**Issue by gimzani** [horprogs/Just-validate#40]
First - I LOVE THIS LIBRARY!  Thank you!

There is only one feature I need. Could you please make the "rule config" so that I could target where the error is appended?  This is critical for compound inputs like this:

``` html
<div class="form-group">
  <label for="oldPassword">Current Password:</label>
  <div class="input-group"> <!-- I want to target this one.  :) -->
    <input type="password" id="oldPassword" name="oldPassword" v-model="req.oldPassword" />
    <button class="btn" @click="show.oldPassword = !show.oldPassword">
        <font-awesome-icon icon="eye-slash" v-if="show.oldPassword"></font-awesome-icon>
        <font-awesome-icon icon="eye" v-else></font-awesome-icon>
    </button>
    <!-- JV currenyly appends here.  No Good.  :(  -->
  </div>
  <!-- I want it to append here instead.  :) -->
</div>
```

If this could also be a "global config" that would be cool too.

I hope this is a quick win?

Other than that, your library is freaking awesome!  Thank you so much for creating it.

**Comment by gimzani** [comment]
To clarify:  I'm not asking to change the default behavior - (it's awesome as is!), - just the ability to optionally target a location to append the errors.

Oh!  Just thought of this!  If you did the optional append, it would allow for an "Error Summary" section, right out of the box.

I don't use them in my apps, but I know that some devs love them.  Bonus win!  :)

Cheers!

**Comment by horprogs** [comment]
Thank you for the feedback and suggestion! This one makes sense for me, I'll look into that

**Comment by horprogs** [comment]
Added `errorsContainer` (both per separate field and globally) setting to define a custom html container where to render the errors. https://just-validate.dev/examples/#errors-container

```
const validation = new JustValidate('#errors-container-form', {
  errorsContainer: '#example11_errors-container',
});

validation
  .addField(
    '#example11_name',
    [
      {
        rule: 'required' as Rules,
        errorMessage: 'Name is required',
      },
    ],
    {
      errorsContainer: '#example11_group-errors-container',
    }
  )
  .addRequiredGroup(
    '#example11_read_terms_checkbox_group',
    'You should select at least one communication channel',
    {
      errorsContainer: '#example11_group-errors-container',
    }
  );
```

**Comment by gimzani** [comment]
Awesome!

I will pull this and test it.  

Thank you SO much for doing this! I hope that it makes your code a lot more popular.  (I'll certainly sing your praises!)  :)

THANK YOU!!!   🥇
