### ISSUE TITLE
Why is the node version fixed to 16.x only?

### ISSUE THREAD

**Issue by piotrkulpinski** [horprogs/Just-validate#48]
Hi, 

Is there any reason why node version is fixed to 16.x?

Thanks

**Comment by horprogs** [comment]
Hi, this is for the bundle building purposes only. 16.x is a stable version at this time. No specific reason for that.

**Comment by piotrkulpinski** [comment]
This prevents me from installing the package with any other version of node. It won't even work with the latest version (17.4.0). 

> yarn add just-validate
yarn add v1.22.17
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error just-validate@3.3.4: The engine "node" is incompatible with this module. Expected version "16.x". Got "17.4.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by horprogs** [comment]
17 is the latest, but not stable yet. I'll look to add 16 and higher versions, just need to make sure everything builds fine. Not expecting any issues though.

**Comment by horprogs** [comment]
Removed `engines` from package.json, tested, seems everything works fine. Now you should be able to use any node.js version

**Comment by piotrkulpinski** [comment]
@horprogs For some reason I still couldn't install it with other version (maybe a cache issue?):

> yarn add just-validate
yarn add v1.22.17
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error just-validate@3.4.0: The engine "node" is incompatible with this module. Expected version "16.x". Got "14.18.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Anyway, I fixed the issue with `--ignore-engines` param and it looks like it's working.
