### ISSUE TITLE
Method for manual validation

### ISSUE THREAD

**Issue by shivam091** [horprogs/Just-validate#51]
Hi,

I come across a situation to manually call form validations from some logical section written in JavaScript function.

The required feature for me is to show preview of the image only if image file is valid. Image field validations are set in JustValidate and there is method missing to validate the form from the method I have wrote for displaying image preview. I hope, there should be a method to call validations manually from that method. (function validate()). In this case, form was having only one field and it's for image upload.

In another screnario, I am having a form with multiple fields with one file field. In this case as well, I should show image preview, but I don't want validate entire form from the method I used for showing image preview. In this case, I just want to revalidate that perticular file field.

If this two methods could be implemented then they may have signature like:

To manually validate entire form.
```javascript
  document.querySelector("form").validate()
```
and to validate / revalidate single form field:

```javascript
  const fv = new JustValidate("form", {
    ...
  });
  
  fv.revalidateField("#field_name");
  or
  fv.validateField("#field_name");
```

If these two scenarios can be supported with some methods like above then that will be great.

Thank you.

**Comment by horprogs** [comment]
Hi! I guess for the first option you could use existing `validate()` method, like: 
```
const fv = new JustValidate("form", {
    ...
  });
fv.validate()
```

For validating field I'll look into that

**Comment by horprogs** [comment]
I added `revalidate()` and `revalidateField()` methods. Could you check please, does it solve your issue?

**Comment by shivam091** [comment]
I'll check it. Thanks.

**Comment by shivam091** [comment]
Hi,

I was going throgh implementing revalidateField() on browser console, I found that, in both cases (valid image and invalid image), method is returning `undefined` however field is getting revalidated.

How can I get to know that field was valid or not. I think, it should return true or false depending on validation sucess and failure.

First execution is for valid image and second one is for invalid image:
```javascript
avatarForm.revalidateField("#real-file")
-> undefined
avatarForm.revalidateField("#real-file")
-> undefined
```

For reference, I have below added JS

NOTE: $ is function shorthand for document.querySelector

```javascript

if (typeof($(".avatar-form")) != "undefined" && $(".avatar-form") != null) {
    avatarForm = new JustValidate(".avatar-form", {
      errorFieldCssClass: "is-invalid",
      errorLabelCssClass: "invalid-feedback",
      successFieldCssClass: "is-valid",
      successLabelCssClass: "valid-feedback",
      focusInvalidField: true,
      lockForm: false,
      tooltip: {
        position: "top"
      },
    }).onSuccess((event) => {
      event.preventDefault();
      Turbo.navigator.submitForm(event.target);
    }).onFail((fields) => {
      setErrorElementStyles();
    });

    if (typeof($("#real-file")) != "undefined" && $("#real-file") != null) {
      avatarForm.addField("#real-file", [
        {
          rule: "minFilesCount",
          value: 1,
          errorMessage: I18n.t("javascripts.validation_error_messages.avatars.image.required")
        },
        {
          rule: "maxFilesCount",
          value: 1,
          errorMessage: I18n.t("javascripts.validation_error_messages.avatars.image.required")
        },
        {
          rule: "files",
          value: {
            files: {
              extensions: ["jpe", "jpg", "jpeg", "png"],
              minSize: 1 * 10 * 1024,
              maxSize: 2 * 1024 * 1024,
              types: ["image/jpeg", "image/jpg", "image/png"],
            },
          },
          errorMessage: I18n.t("javascripts.validation_error_messages.avatars.image.file")
        },
      ]);
    }
  }
```

**Comment by shivam091** [comment]
Hi.
In addition to above I tried using validate() but it didn't validated form

```
avatarForm.validate();
```

but revalidate() is able to validate the form but it also returned me undefined (I think, it should also return true or false).

```
avatarForm.validate();
-> Promise {<fulfilled>: true}
avatarForm.revalidate();
-> undefined
```

**Comment by shivam091** [comment]
If it is possible then can these method return true/false. so that it can be easier to get to know that the form or field is validated successfully or not and this will help me to show image preview of file only if these methods will return true

Thanks.

**Comment by horprogs** [comment]
Hey, now, `.revalidate()` and `.revalidateField()` methods return a promise (because validation is actually is an async function) with a boolean value: valid or not:

```
validation.revalidateField('#name').then(isValid => {
   
})
```

**Comment by shivam091** [comment]
Okay thank you.

**Comment by shivam091** [comment]
> Okay thank you.

I will look into this
