### ISSUE TITLE
Few identical forms on the page

### ISSUE THREAD

**Issue by pow44feet** [horprogs/Just-validate#54]
I saw few similar issues here, still want to know if any change: i create few identical forms with identical classes on the page. Could i sort out its into js cycle or need to create individual JustValidate object for every form?

**Comment by horprogs** [comment]
You should do it using the cycle, like this:

```
['#create-project, #edit-project'].forEach((selector) => {
  const formValidation = new JustValidate(selector, {
    errorFieldCssClass: 'is-invalid',
    errorLabelCssClass: 'invalid-feedback',
    focusInvalidField: true,
    lockForm: false,
    tooltip: {
      position: 'top',
    },
  })
    .addField(`${selector}-name`, [
      {
        rule: 'required',
      },
    ])
    .onSuccess((event) => {
      event.preventDefault();
    })
    .onFail((fields) => {});
});
```

**Comment by horprogs** [comment]
also you could use the same classes for `addField` selector, it would be fine too

**Comment by pow44feet** [comment]
> You should do it using the cycle, like this:
> 
> ```
> ['#create-project, #edit-project'].forEach((selector) => {
>   const formValidation = new JustValidate(selector, {
>     errorFieldCssClass: 'is-invalid',
>     errorLabelCssClass: 'invalid-feedback',
>     focusInvalidField: true,
>     lockForm: false,
>     tooltip: {
>       position: 'top',
>     },
>   })
>     .addField(`${selector}-name`, [
>       {
>         rule: 'required',
>       },
>     ])
>     .onSuccess((event) => {
>       event.preventDefault();
>     })
>     .onFail((fields) => {});
> });
> ```

thanks a lot! i'll try it later
