### ISSUE TITLE
Possible set required rule via HTML without using addField

### ISSUE THREAD

**Issue by weilinzung** [horprogs/Just-validate#55]
**Is your feature request related to a problem? Please describe.**

```
<form>
        <input
          required
          type="text"
          name="firstName"
          placeholder="first name"
        />

        <input
          required
          type="text"
          name="lastName"
          placeholder="last name"
        />
</form>
```

When I have a form like the above, I have to keep repeating using `.addField()`.

**Describe the solution you'd like**
Possible to use all [rules](https://github.com/horprogs/Just-validate#predefined-rules) directly from HTML, then we can just do something like this below. This is useful when needing to set up multiple forms with dynamic required fields.

```
  new JustValidate(
    '#form',
    {
      focusInvalidField: true,
      lockForm: true,
    }
  );
```

 Thanks!

**Comment by horprogs** [comment]
Hi! Thank you, that is an interesting suggestion. I decided to move from defining the rules as html attributes (because it could be different set of rules and it's impossible to define them in the html), but probably it makes sense to implement some kind of a `quick setup`, based on input type and `required`, `min`, `max` (for input type number) attributes. I'll think about it

**Comment by weilinzung** [comment]
hi, this JQ library could be an example: https://parsleyjs.org/doc/index.html.

Ideally people only need to do custom rules from the JS.

**Comment by horprogs** [comment]
I'm not sure honestly. This approach I used in the previous version of this library, but now I think that not touching HTML layout and defining rules in the js config is cleaner solution. Also this is more powerful and customizable way.

I believe these are just 2 different approaches, and I'm not sure which one is better

**Comment by horprogs** [comment]
but I definitely like the idea about a quick setup based on native html attributes, like `required` etc

**Comment by weilinzung** [comment]
For my case(multiple similar forms), I would like the HTML way better.

**Comment by Basster** [comment]
Because I had the same need, I'm going to leave this snipped here:

```js
/**
 * @callback CustomRulesFactory
 * @param {Rule[]} rules - An array of rule the calling script has already detected.
 * @param {HTMLInputElement} input - The HTML input element to validate
 * @returns {Rule[]} An array of Rule objects with validation results. Either merged
 *    with the input rules or completely modified.
 */

/**
 * @param {Element} input
 * @param {CustomRulesFactory} customRulesFactory
 * @returns {Rule[]}
 */
export const generateRulesFromAttributes = (input, customRulesFactory = undefined) => {
  const rules = [];

  if (input.hasAttribute('required')) {
    rules.push({ rule: 'required' });
  }

  if (input.type === 'email') {
    rules.push({ rule: 'email' });
  }

  if (input.hasAttribute('minlength')) {
    rules.push({ rule: 'minLength', value: parseInt(input.getAttribute('minlength'), 10) });
  }

  if (input.hasAttribute('maxlength')) {
    rules.push({ rule: 'maxLength', value: parseInt(input.getAttribute('maxlength'), 10) });
  }

  if (input.hasAttribute('pattern')) {
    rules.push({ rule: 'customRegexp', value: input.getAttribute('pattern') });
  }

  if (input.type === 'number') {
    if (input.hasAttribute('min')) {
      rules.push({ rule: 'minNumber', value: parseFloat(input.getAttribute('min')) });
    }
    if (input.hasAttribute('max')) {
      rules.push({ rule: 'maxNumber', value: parseFloat(input.getAttribute('max')) });
    }
  }

  if (customRulesFactory) {
    rules.push(...customRulesFactory(rules, input));
  }

  return rules;
};
```

Enjoy
