### ISSUE TITLE
Conflicting variable name with Underscore.js

### ISSUE THREAD

**Issue by rob-howells** [horprogs/Just-validate#60]
**Overview**
When using JustValidate on a site that also uses Underscore.js, I'm seeing an issue with the variable `var _ = Object.defineProperty` (taken from https://unpkg.com/just-validate@3.5.1/dist/just-validate.production.min.js). Both libraries are creating global `_` variables, which can cause an error in code that is using Underscore

**To Reproduce**
1. Go to the following [codepen](https://codepen.io/RobHowells/pen/wvpNGNP), where both JustValidate and Underscore are included
2. View the console
3. See `Uncaught TypeError: _.defer is not a function` error

**Suggested action**
Update global variable name to something that doesn't clash with Underscore - are there any wider considerations to this?

**Comment by horprogs** [comment]
Hi, thank you for the reporting. This is interesting, because this variable added by building tools for UMD. I'm looking into that.

**Comment by horprogs** [comment]
Should be fixed now. Was caused by some issues in `vite` (https://github.com/vitejs/vite/issues/5426)

**Comment by rob-howells** [comment]
Thanks @horprogs! That's resolved that issue 👍
