### ISSUE TITLE
Feature Request: CSS class configuration options accept multiple class names

### ISSUE THREAD

**Issue by erobertson42** [horprogs/Just-validate#61]
**Is your feature request related to a problem? Please describe.**

The various CSS class configuration options (`errorFieldCssClass`, `errorLabelCssClass`, `successFieldCssClass`, `successLabelCssClass`) only accept a single class name.  If I try to add multiple, an error is thrown.

**Describe the solution you'd like**

It would be beneficial to be able to set multiple class names for these configuration options.  I envision being able to specify a space delimited class list.  For example (using Bootstrap 5 classes):
```javascript
{
  errorFieldCssClass: 'border-danger border-2'
}
```
This should be fairly simple with only a small refactor to any calls to `elem.classList` methods.  For example, in `main.ts`:

https://github.com/horprogs/Just-validate/blob/cb4a94577f6a89d870a3638522ed5787bac163ef/src/main.ts#L1478-L1480
... would become something like ...
```javascript
    field.elem.classList.add(
      field.config?.errorFieldCssClass?.trim()?.length
        ? ...field.config.errorFieldCssClass.split(' ').filter(cls => cls.length > 0)
        : this.globalConfig.errorFieldCssClass
    );
```
I turned it into a ternary because the spread operator will throw an error if the optional chaining fails, and the `filter()` call is just some error checking to toss out any empty array items, in case the user accidentally put multiple spaces between class names.  Anyway, you get the idea.

**Describe alternatives you've considered**

If you wanted to get fancy, you could also accept an array of class names, in addition to the space delimited class list, but that's just icing.

&nbsp;

Also, great library, btw.  I just started using it.

Do you consider/accept/appreciate pull requests?  I seems you may prefer to discuss a topic first and implement it yourself, which I totally understand.  Just trying to get a sense of things, I may have another feature request or two on my mind.  🙂

**Comment by horprogs** [comment]
Hi! Yeah great suggestion! Your solution will work, also yeah we could do it as `string | string[]` and check if it's an array. Would be useful.

I really appreciate pull requests - if you could do that, you are warmly welcome! :)

**Comment by horprogs** [comment]
Thanks again for the suggestion! Implemented in `3.7.0` 🚀

If you have more suggestions - you are welcome to create issues/PRs!

**Comment by erobertson42** [comment]
Great, thank you!

**Comment by erobertson42** [comment]
Thank you, this is working great, however, I did find a potential issue.  If the user accidentally adds multiple spaces between the class names, an error will be thrown.  A quick pass through `.filter()` should take care of it:

https://github.com/horprogs/Just-validate/blob/ed08c6550b43ae9e88823ed60e6a117836af4a24/src/utils/helperUtils.ts#L46

tweaked to:

```javascript
list.push(...classList.split(' ').filter(cls => cls.length > 0));
```
(with the `.filter()`, `.trim()` is no longer necessary)

I get that _technically_ it's a user error, but if you don't know what the code is doing behind the scenes it may not be obvious, and it's such a simple preventative fix.

Thanks again!

**Comment by horprogs** [comment]
Good catch, indeed! Fixed
