### ISSUE TITLE
Disabled button in the form getting enabled on validation

### ISSUE THREAD

**Issue by HemendraSingh** [horprogs/Just-validate#62]
**Describe the bug**
I have a disabled button called "Delete" which is disabled.
On Validation Fail/Success the "Delete" button disabled attribute is removed and it becomes enabled.

**To Reproduce**
1. Have a Form with 2 or more buttons. One is submit and the other one is of type button and is disabled.
2. Click on Submit and the other disabled button becomes enabled.
3. The disabled attribute is removed and is replace by style with no value.

**Expected behavior**
The disabled button should not become enabled.

**Comment by HemendraSingh** [comment]
Just an Update.
For anyone who has faced this issue, I have found a workaround to this by keeping the button outside the form and triggering .revalidate().then(isValid => {}) function on button click event.

**Comment by horprogs** [comment]
Hi! Great catch, indeed, all buttons and inputs are being disabled/enabled during the validation. You could change `lockForm` to `false`, as a workaround (probably you even don't need it). 

```
const validation = new JustValidate('#form', {
    lockForm: false,
  });
```
In that case the library will not disable/enable anything. In the meanwhile I will fix it. Thanks.

**Comment by HemendraSingh** [comment]
@horprogs  Thanks a lot. Have a great day.

**Comment by horprogs** [comment]
Release a small fix

**Comment by HemendraSingh** [comment]
@horprogs  Thanks. It is working as expected. Great work.

**Comment by saiballo** [comment]
Hello, 
I'm last version of justvalidate and the issue is still present. The workround to prevent this ("lockForm": false) it's working. Where I'm wrong?

**Comment by saiballo** [comment]
any news about my last comment? I think the bug is still present

**Comment by evdeveloper** [comment]
> any news about my last comment? I think the bug is still present

you need to listen to isValid in the onValidate method
.onValidate(function({ isValid }) {
      const form = this.form;
      const button = form.querySelector('button[type="submit"]');
      isValid ? button.disabled = false : button.disabled = true;
    });

**Comment by hijiki0127** [comment]
Hi,
I have the same problem(maybe).

My form has some disabled input fields that attached no validation rules.
When form is validate, disabled attribute is removed.

I hope that the disabled input fields are hold disabled attribute.
