### ISSUE TITLE
Adding class in ajax response

### ISSUE THREAD

**Issue by muhammedcamsari** [horprogs/Just-validate#63]
Greetings from Turkey,

I have a question for version 3.5. After Ajax response, what to do to add Bootstrap 'invalid-feedback' to input?

I am designing login page and I need to add warning text to input for wrong password. Jquery is not being added with 'class.add' attribute.
```html
<div class="col-12">
    <label>E-Mail</label>
    <input type="email" class="form-control" id="email">
    <div class="invalid-feedback" id="emailerror">
    </div>
</div>
```

```js

const validation = new JustValidate('#GirisForm', {
validation.addField('#email', [
{
	rule: 'required',
]) ).onSuccess((event) => {
   $.ajax({
	type:"POST",
	url: "login/", 
	data:{email: email},
	    success: function(data) { }
       });
});

```

**Comment by horprogs** [comment]
I added `.showErrors()` method, so you could call it as `validation.showErrors({ '#password': 'The password is invalid' })` to show the errors programmatically.

https://just-validate.dev/examples/#show-errors
https://just-validate.dev/documentation/#section-5-11

**Comment by muhammedcamsari** [comment]
Wonderful! `.showErrors() `is running. Thanks for the feature.
