### ISSUE TITLE
reverse function property for showErrors

### ISSUE THREAD

**Issue by muhammedcamsari** [horprogs/Just-validate#66]
Greetings from Turkey.

Can you add reverse operation for showError function? The showSuccess field wouldn't be bad at all. This feature is required when using with Promise.

**Comment by muhammedcamsari** [comment]
Also one more question. Below is an example. The back server also checks if E-Mail is used. How can it be considered validated based on the sample?



```js
{
validator: (value, context) => () =>
	new Promise((resolve, reject) => {
		$.ajax({
			type: 'POST',
			url: '/register/',
			data: {
				value: context['#mail'].elem.value,
			},
			success: function (data) {

				if (data.is_email == 'True' ) {
			         // ?? //
				} else if (data.is_email == 'False' ) {
                                        validation.showErrors( {
						'#mail': 'Mail used.' 
					});

			},
			error: function () {	
			},
		});
}),
}
```

data.is_email

**Comment by horprogs** [comment]
Hello, sorry for the late response. For you second question you should explicitly specify `true` in `resolve`, like this: `resolve(true)`. I know it could be confusing, I'll adjust the docs.

`showSuccess` looks good yeah agreed, I will add as well

**Comment by horprogs** [comment]
Added `showSuccessLabels` method in `3.8.0`. Thanks for the suggestion!

Example:
https://just-validate.dev/examples/#show-errors
