### ISSUE TITLE
Conditional validation not working on `change` event

### ISSUE THREAD

**Issue by shivam091** [horprogs/Just-validate#67]
**Describe the bug**
I noticed that condition validation as you mentioned in your example don't work on change event.
I have a select list and depending on the select list input, I want to validate checkbox's `checked` attribute.

It gives error as 

`Field not found. Check the field selector`

**To Reproduce**
1. Add one checkbox and select list with some elements.
2. Add validation like below to 
```javascript
document.querySelector("[name='user[notification_settings_attributes][is_delay_enabled]']").addEventListener("change", (event) => {
      if (event.target.value === "") {
        this.notificationPreferencesFormValidator.removeField("[name='user[notification_settings_attributes][is_delay_enabled]']");
      } else {
        this.notificationPreferencesFormValidator.addField("[name='user[notification_settings_attributes][is_delay_enabled]']", [
          {
            rule: "required",
            errorMessage: "Must be checked"
          },
        ]);
      }
    });
```

**Expected behavior**
It should also listen properly to change event.

Thank you.

**Comment by shivam091** [comment]
This also happen in case of checkbox's change event. When I programatically change `checked` proerty of the checkbox, it throws above mentioned error. click event works but it's not useful when I change it programatically.

**Comment by horprogs** [comment]
Thanks for the reporting, could you please create a reproduction example using this template https://codesandbox.io/s/just-validate-template-jrv65?file=/index.html?

**Comment by shivam091** [comment]
Hey..

I found the issue. The issue was due to backend framework (Rails) I am using.

The framework adds two elements for check box field. One hidden field and other actual checkbox. Both these has same name.

Setting unique id to actualy checkbox element has resolved that problem.

Btw. Thank you because while reproducing that issue on sandbox, I noticed this.
