### ISSUE TITLE
Support for dynamically added form fields

### ISSUE THREAD

**Issue by shivam091** [horprogs/Just-validate#68]
Hello,

Is there any way at present or in future for validating dynamically added fields with indexed id and name for form elements ?

It would be better and useful if the library has such a feature to validate dynamically added fields.

Previously I was on formvalidation.io where I had seen such an example and now a days it's the requirement in my application.

Below example you can refer if you find it helpful.
[Example](https://formvalidation.io/guide/examples/adding-dynamic-field/)

Thank you.

**Comment by horprogs** [comment]
It works even with nested groups: https://codepen.io/Horprogs/pen/yLvYMGV

**Comment by shivam091** [comment]
Hey..

I found the issue. The issue was due to backend framework (Rails) I am using.

The framework adds two elements for check box field. One hidden field and other actual checkbox. Both these has same name.

Setting unique id to actualy checkbox element has resolved that problem.

Btw. Thank you because while reproducing that issue on sandbox, I noticed this.

**Comment by horprogs** [comment]
Hey @shivam091 do you still have some issues? Or I could close this one

**Comment by shivam091** [comment]
I am trying this by refering above two urls but till now I didn't get success. Those two urls are showing something else which I am not yet able to fit in my code.

I am getting elements with almost same name with only difference is that they have timestamp in it.

e.g. after submitting form and going to update that same record -> task[tasks_links_attributes][1][link_type], task[tasks_links_attributes][2][link_type] 

for fresh record those attributes are like -> task[tasks_links_attributes][1655345231414][link_type], task[tasks_links_attributes][1655345232373][link_type]

I am still trying how I can validate such type of fields

**Comment by shivam091** [comment]
Yes definitely.. I am preparing exact replica of that form on sandbox with some validations.
