### ISSUE TITLE
does not submit

### ISSUE THREAD

**Issue by Mlouden** [horprogs/Just-validate#75]
I have followed the documentation provided here : https://just-validate.dev/documentation, but it doesnt submit.
Here is the code : 
![validator](https://user-images.githubusercontent.com/37013135/175463886-74c427f1-a801-4194-ac55-4fe75a0165b7.JPG)

UPDATE :  I have to add this line of code, it's not mentionned in the docs.
![validator](https://user-images.githubusercontent.com/37013135/175468034-5779738e-4a38-4a2c-a05e-1c4f773a29b3.JPG)

I have an other issue:  in the same  code, when I leave the input blank, it's considered as success...

**Comment by horprogs** [comment]
Could you please put your code here https://codesandbox.io/s/just-validate-template-jrv65?file=/index.html to provide an example.

About the second issue: you could check this explanation: https://github.com/horprogs/Just-validate/issues/59, in short words you should also use `required` rule

**Comment by horprogs** [comment]
Ah I get your point, you could check this issue https://github.com/horprogs/Just-validate/issues/72

As we have a few of such issues I'll think how to change this behaviour. But yeah for now you should trigger the submitting manually if you want to do a regular submit (not ajax)

**Comment by Mlouden** [comment]
Thank you for your answers ! it's works perfect now !

**Comment by grstreten** [comment]
Perhaps this could be pinned as an FYI somewhere? Took me a min to figure this :)

**Comment by horprogs** [comment]
Yeah, good idea, agreed, I'll add a setting to handle this and add it to the docs. Thanks!
