### ISSUE TITLE
errorContainer, doesn't work.

### ISSUE THREAD

**Issue by alihs** [horprogs/Just-validate#76]
The field for 'errorContainer' doesn't work.
There is no mention of if it in the js as well.

**Comment by horprogs** [comment]
Hey, have you checked this example? https://just-validate.dev/examples/#errors-container
Just in case it's called `errorsContainer`, not `errorContainer`

**Comment by Rocketpilot** [comment]
Yeah I'm having similar issues - no matter how I configure the script, the error message stubbornly inserts into directly before the closing </form> tag. 

As best as I can tell, it should be possible to add to each addRule block a config setting that tells the script to add error text into a specific DIV inside the markup, but that doesn't happen. I don't really like the presentation of the tooltip, but it's the only way to currently get the error message anywhere near the erroring input.

**Comment by horprogs** [comment]
Could you please provide any example? I created a small one here and it works properly. 

https://codesandbox.io/s/just-validate-template-forked-4yf98v?file=/index.html

<img width="590" alt="image" src="https://user-images.githubusercontent.com/14051960/180425775-539249ed-3a39-4933-bd5e-37f9212657f7.png">

**Comment by horprogs** [comment]
But now it's not possible to specify the error container for the each particular field. Only for everything together. Yeah it's a good point actually to make it possible, thanks. I'll look into that

**Comment by Rocketpilot** [comment]
> But now it's not possible to specify the error container for the each particular field. Only for everything together. Yeah it's a good point actually to make it possible, thanks. I'll look into that

Yes that's the scenario I'm talking about - an addition like that would make this an extremely versatile tool.

**Comment by jpeszleny** [comment]
I'm facing the same issue. An error container for each rule is much more ideal.

**Comment by horprogs** [comment]
Sorry guys, as it turned out I implemented the support for the custom error container for the particular field a long time ago, just forgot about it. Documentation was misleading, fixed it. The correct name of the config: `errorsContainer`. It works both for the globally defined and field-by-field.

You could check it out here: https://codesandbox.io/s/just-validate-template-forked-gj11bj?file=/index.html and here https://just-validate.dev/examples/#errors-container

**Comment by jpeszleny** [comment]
> Sorry guys, as it turned out I implemented the support for the custom error container for the particular field a long time ago, just forgot about it. Documentation was misleading, fixed it. The correct name of the config: `errorsContainer`. It works both for the globally defined and field-by-field.
> 
> You could check it out here: https://codesandbox.io/s/just-validate-template-forked-gj11bj?file=/index.html and here https://just-validate.dev/examples/#errors-container

Perfect! Works great! Thanks!
