### ISSUE TITLE
Use with Typescript and esbuild

### ISSUE THREAD

**Issue by damianostre** [horprogs/Just-validate#77]
**Describe the bug**
Hi, thanks for your work!
I'm trying to use just-validate with typescript and bundle it with esbuild. Unfortunately esbuild is not able to import Rules enum from types definition.

**To Reproduce**
package.json
```
"devDependencies": {
    "esbuild": "^0.15.5",
    "typescript": "^4.7.4"
  },
  "dependencies": {
    "just-validate": "^3.8.1"
  }
```

index.ts
```
import JustValidate from "just-validate";
import { Rules } from "just-validate/dist/modules/interfaces";

const validate = new JustValidate("#form");
validate.addField("#field", [{
    rule: Rules.Required
}]);
```

Cmd to build:
` ./node_modules/.bin/esbuild index.ts --bundle --outfile=index.js`

**Error**
![image](https://user-images.githubusercontent.com/2311840/187072193-7814a0ab-71d5-427a-be39-3d270cf0d5e9.png)

Thanks!

**Comment by horprogs** [comment]
Hello, I had a quick look to the build. It seems I need some time or help to understand how to expose types correctly.
