### ISSUE TITLE
Regex for strongPassword

### ISSUE THREAD

**Issue by gavrochelegnou** [horprogs/Just-validate#80]
Hello, 

The current regex for strongPassword is missing many special caracters, and if we include any caracter other than those listed the password is rejected (for example a password including a dot, brace, bracket, or any diacritics ...)

I'd recommend using this regex that requires at least one (and allows) caracter other than A-Za-z0-9.

`(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^A-Za-z0-9])(?=.{8,})`

Thanks for the great lib !

**Comment by horprogs** [comment]
Hello, thanks! I think it's better for people to use `customRegexp` field for now, as I cannot change the existing rule because it would be a breaking change. I'll keep this in mind just in case if someday will be the major version of the lib :)

**Comment by gavrochelegnou** [comment]
Ok sure, 

It might just be worth explaining in the readme/doc what strongPassword really do, because i had a hard time understanding why a password just generated from a complex password generator (like `7LV.ru#sQ&do` )  was considered insecure :)

Thanks
