### ISSUE TITLE
Provide unminified js version

### ISSUE THREAD

**Issue by nhaberl** [horprogs/Just-validate#87]
Instaed of having the min.js file available over unpkg it would be geat to have the unminified version to host and bundle ourselves or over my cdn.
Currently there is no full js version.

Thanks a lot!

**Comment by horprogs** [comment]
Hi! But why do you need the unminified version? 

If for some reason you need the source, there is unminified and non transpiled version (with classes, exports etc) https://unpkg.com/browse/just-validate@3.8.1/dist/just-validate.es.js
