### ISSUE TITLE
Broken link on date plugin CDN

### ISSUE THREAD

**Issue by kpatron** [horprogs/Just-validate#89]
The link to the date plugin CDN at https://unpkg.com/just-validate@latest/dist/just-validate-plugin-date.production.min.js doesn't seem to work. Is this intentional? I haven't tried using NPM for it

**Comment by horprogs** [comment]
The correct link is https://unpkg.com/browse/just-validate-plugin-date@latest/dist/just-validate-plugin-date.production.min.js

Fixed README, thanks for the catch
