### ISSUE TITLE
My submit button is actually an input element

### ISSUE THREAD

**Issue by bezlashkari** [horprogs/Just-validate#99]
Hello, I'm not sure if this is currently possible and I just don't know how to get it to work but I'm using this library for some Drupal 9 webform validation. Unfortunately the Drupal submit action is controlled by an input element and not a button.

<input class="webform-button--submit button--primary js-form-submit form-submit btn btn-primary" data-twig-suggestion="webform-submission-test-add-form" data-drupal-selector="edit-submit" type="submit" id="edit-submit" name="op" value="Submit">

Is there anyway I can get the Just Validate library to work with an input element for submission rather than a button?

Thanks,
Bez

**Comment by horprogs** [comment]
Hi! The library catches `submit` event. Not sure how Drupal works, but I guess you could manually fire a submit event, like this:
```
           document.querySelector("#submit").addEventListener("click", () => {
              document.querySelector("#basic_form").requestSubmit();
            });
```

So you can use any element, click on that and then call a `requestSubmit` form method.

Created an example here https://codesandbox.io/s/just-validate-template-forked-v49lcv?file=/index.html
